comprimir:
	(cd Arduino; make)
	(cd ArduinoYAppAndroid; make)
	(cd ArduinoYBluetooth; make)
	(cd ArduinoYLaWeb2; make)
	(cd ArduinoYServerWeb; make)
	(cd ArduinoYSpacebrew; make)
	
.phony: clean
clean:
	(cd Arduino; make clean)
	(cd ArduinoYAppAndroid; make clean)
	(cd ArduinoYBluetooth; make clean)
	(cd ArduinoYLaWeb2; make clean)
	(cd ArduinoYServerWeb; make clean)
	(cd ArduinoYSpacebrew; make clean)

.phony: pdfmenos
pdfmenos:
	(cd Arduino; make pdfmenos)
	(cd ArduinoYAppAndroid; make pdfmenos)
	(cd ArduinoYBluetooth; make pdfmenos)
	(cd ArduinoYLaWeb2; make pdfmenos)
	(cd ArduinoYServerWeb; make pdfmenos)
	(cd ArduinoYSpacebrew; make pdfmenos)
