comprimir:
	(cd MinisterioSaludSV; make)
	(cd Rss; make)
	
.phony: clean
clean:
	(cd MinisterioSaludSV; make clean)
	(cd Rss; make clean)

.phony: pdfmenos
pdfmenos:
	(cd MinisterioSaludSV; make pdfmenos)
	(cd Rss; make pdfmenos)
 
